// Import the functions you need
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.3.0/firebase-app.js";
import {
  getFirestore,
  collection,
  addDoc,
} from "https://www.gstatic.com/firebasejs/10.3.0/firebase-firestore.js";
import {
  getAuth,
  createUserWithEmailAndPassword,
} from "https://www.gstatic.com/firebasejs/10.3.0/firebase-auth.js";

// Firebase config
const firebaseConfig = {
  apiKey: "AIzaSyC2560pETTPekmI-ABPf_xZ3M3UB6ZqMK4",
  authDomain: "message-display-system.firebaseapp.com",
  projectId: "message-display-system",
  storageBucket: "message-display-system.appspot.com",
  messagingSenderId: "260068152843",
  appId: "1:260068152843:web:2336283608fddc0e41d90e",
  measurementId: "G-HCK0JW6RYC",
};

// Initialize Firebase and Firestore
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth();

// function to add an event to Firestore database
export async function addEventToFirestore(event) {
  try {
    const eventData = {
      ...(event.eventName && { eventName: event.eventName }),
      ...(event.eventCategory && { eventCategory: event.eventCategory }),
      ...(event.eventLocation && { eventLocation: event.eventLocation }),
      ...(event.eventDate && { eventDate: event.eventDate }),
      ...(event.organiserName && { organiserName: event.organiserName }),
      ...(event.time && {time: event.time }),
      ...(event.wifi && { wifi: event.wifi }),
    };

    await addDoc(collection(db, "eventsCreated"), eventData);
    console.log("New event successfully added!");
  } catch (error) {
    console.error("Error adding new event: ", error);
  }
}

// function to register user using
export async function registerUser(user) {
  try {
    // Create a new user account using Firebase Authentication
    const userCredential = await createUserWithEmailAndPassword(
      auth,
      user.email,
      user.password
    );

    // Log a success message for Firebase Authentication
    console.log(
      "New user has been successfully registered with Firebase Authentication."
    );

    // Extract the user object from the returned user credentials
    const firebaseUser = userCredential.user;

    // Prepare the user data to be stored in Firestore
    // Include the unique user ID generated by Firebase Authentication
    const userData = {
      uid: firebaseUser.uid,
      ...(user.username && { username: user.username }),
      ...(user.email && { email: user.email }),
      ...(user.preference && { preference: user.preference }),
    };

    // Store the prepared user data in Firestore
    await addDoc(collection(db, "UserList"), userData);
    console.log(
      "New user has been successfully registered and added to Firestore!"
    );
  } catch (error) {
    console.error("An error occurred while registering a new user: ", error);
  }
}
